var jugadores =[
    { "id": 1, "idjugador": 1, "nombre": "milton", "seleccion": "QATAR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 1, "idjugador": 1, "nombre": "jhon", "seleccion": "QATAR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 2, "idjugador": 1, "nombre": "milton", "seleccion": "ALEMANIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 2, "idjugador": 1, "nombre": "jhon", "seleccion": "ALEMANIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 3, "idjugador": 1, "nombre": "milton", "seleccion": "DINAMARCA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 3, "idjugador": 1, "nombre": "jhon", "seleccion": "DINAMARCA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 4, "idjugador": 1, "nombre": "milton", "seleccion": "BRASIL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 4, "idjugador": 1, "nombre": "jhon", "seleccion": "BRASIL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 5, "idjugador": 1, "nombre": "milton", "seleccion": "FRANCIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 5, "idjugador": 1, "nombre": "jhon", "seleccion": "FRANCIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 6, "idjugador": 1, "nombre": "milton", "seleccion": "BELGICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 6, "idjugador": 1, "nombre": "jhon", "seleccion": "BELGICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 7, "idjugador": 1, "nombre": "milton", "seleccion": "CROACIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 7, "idjugador": 1, "nombre": "jhon", "seleccion": "CROACIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 8, "idjugador": 1, "nombre": "milton", "seleccion": "ESPAÑA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 8, "idjugador": 1, "nombre": "jhon", "seleccion": "ESPAÑA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 9, "idjugador": 1, "nombre": "milton", "seleccion": "SERBIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 9, "idjugador": 1, "nombre": "jhon", "seleccion": "SERBIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 10, "idjugador": 1, "nombre": "milton", "seleccion": "INGLATERRA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 10, "idjugador": 1, "nombre": "jhon", "seleccion": "INGLATERRA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 11, "idjugador": 1, "nombre": "milton", "seleccion": "SUIZA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 11, "idjugador": 1, "nombre": "jhon", "seleccion": "SUIZA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 12, "idjugador": 1, "nombre": "milton", "seleccion": "PAISES BAJOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 12, "idjugador": 1, "nombre": "jhon", "seleccion": "PAISES BAJOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 13, "idjugador": 1, "nombre": "milton", "seleccion": "ARGENTINA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 13, "idjugador": 1, "nombre": "jhon", "seleccion": "ARGENTINA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 14, "idjugador": 1, "nombre": "milton", "seleccion": "IRAN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 14, "idjugador": 1, "nombre": "jhon", "seleccion": "IRAN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 15, "idjugador": 1, "nombre": "milton", "seleccion": "COREA DEL SUR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 15, "idjugador": 1, "nombre": "jhon", "seleccion": "COREA DEL SUR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 16, "idjugador": 1, "nombre": "milton", "seleccion": "JAPON", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 16, "idjugador": 1, "nombre": "jhon", "seleccion": "JAPON", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 17, "idjugador": 1, "nombre": "milton", "seleccion": "ARABIA SAUDITA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 17, "idjugador": 1, "nombre": "jhon", "seleccion": "ARABIA SAUDITA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 18, "idjugador": 1, "nombre": "milton", "seleccion": "ECUADOR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 18, "idjugador": 1, "nombre": "jhon", "seleccion": "ECUADOR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 19, "idjugador": 1, "nombre": "milton", "seleccion": "URUGUAY", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 19, "idjugador": 1, "nombre": "jhon", "seleccion": "URUGUAY", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 20, "idjugador": 1, "nombre": "milton", "seleccion": "CANADA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 20, "idjugador": 1, "nombre": "jhon", "seleccion": "CANADA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 21, "idjugador": 1, "nombre": "milton", "seleccion": "GHANA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 21, "idjugador": 1, "nombre": "jhon", "seleccion": "GHANA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 22, "idjugador": 1, "nombre": "milton", "seleccion": "SENEGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 22, "idjugador": 1, "nombre": "jhon", "seleccion": "SENEGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 23, "idjugador": 1, "nombre": "milton", "seleccion": "MARRUECOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 23, "idjugador": 1, "nombre": "jhon", "seleccion": "MARRUECOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 24, "idjugador": 1, "nombre": "milton", "seleccion": "TUNEZ", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 24, "idjugador": 1, "nombre": "jhon", "seleccion": "TUNEZ", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 25, "idjugador": 1, "nombre": "bichardo", "seleccion": "PORTUGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 25, "idjugador": 1, "nombre": "bicho", "seleccion": "PORTUGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 26, "idjugador": 1, "nombre": "milton", "seleccion": "POLONIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 26, "idjugador": 1, "nombre": "jhon", "seleccion": "POLONIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 27, "idjugador": 1, "nombre": "milton", "seleccion": "CAMERUN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 27, "idjugador": 1, "nombre": "jhon", "seleccion": "CAMERUN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 28, "idjugador": 1, "nombre": "milton", "seleccion": "MEXICO", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 28, "idjugador": 1, "nombre": "jhon", "seleccion": "MEXICO", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 29, "idjugador": 1, "nombre": "milton", "seleccion": "ESTADOS UNIDOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 29, "idjugador": 1, "nombre": "jhon", "seleccion": "ESTADOS UNIDOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 30, "idjugador": 1, "nombre": "milton", "seleccion": "GALES", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 30, "idjugador": 1, "nombre": "jhon", "seleccion": "GALES", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 31, "idjugador": 1, "nombre": "milton", "seleccion": "AUSTRALIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 31, "idjugador": 1, "nombre": "jhon", "seleccion": "AUSTRALIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 32, "idjugador": 1, "nombre": "milton", "seleccion": "COSTA RICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
{ "id": 32, "idjugador": 1, "nombre": "jhon", "seleccion": "COSTA RICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
]