var paises2 = [
    { "id": 1, "nombre": "QATAR", "continente": "ASIA", "participaciones": 1, "goles": 1, "golesencontra": 0, "faltas": 1, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 2, "nombre": "ALEMANIA", "continente": "EUROPA", "participaciones": 2, "goles": 1, "golesencontra": 0, "faltas": 2, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 3, "nombre": "DINAMARCA", "continente": "EUROPA", "participaciones": 3, "goles": 2, "golesencontra": 0, "faltas": 3, "puntos": 2, "difgoles": 0, "identificador": null },
    { "id": 4, "nombre": "BRASIL", "continente": "AMERICA DEL SUR", "participaciones": 4, "goles": 4, "golesencontra": 0, "faltas": 4, "puntos": 6, "difgoles": 0, "identificador": null },
    { "id": 5, "nombre": "FRANCIA", "continente": "EUROPA", "participaciones": 5, "goles": 6, "golesencontra": 0, "faltas": 5, "puntos": 8, "difgoles": 0, "identificador": null },
    { "id": 6, "nombre": "BELGICA", "continente": "EUROPA", "participaciones": 6, "goles": 3, "golesencontra": 0, "faltas": 6, "puntos": 9, "difgoles": 0, "identificador": null },
    { "id": 7, "nombre": "CROACIA", "continente": "EUROPA", "participaciones": 7, "goles": 1, "golesencontra": 0, "faltas": 6, "puntos": 1, "difgoles": 0, "identificador": null },
    { "id": 8, "nombre": "ESPAÑA", "continente": "EUROPA", "participaciones": 8, "goles": 6, "golesencontra": 0, "faltas": 7, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 9, "nombre": "SERBIA", "continente": "EUROPA", "participaciones": 9, "goles": 8, "golesencontra": 0, "faltas": 8, "puntos": 6, "difgoles": 0, "identificador": null },
    { "id": 10, "nombre": "INGLATERRA", "continente": "EUROPA", "participaciones": 10, "goles": 8, "golesencontra": 0, "faltas": 9, "puntos": 6, "difgoles": 0, "identificador": null },
    { "id": 11, "nombre": "SUIZA", "continente": "EUROPA", "participaciones": 11, "goles": 9, "golesencontra": 0, "faltas": 0, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 12, "nombre": "PAISES BAJOS", "continente": "EUROPA", "participaciones": 12, "goles": 2, "golesencontra": 0, "faltas": 10, "puntos": 9, "difgoles": 0, "identificador": null },
    { "id": 13, "nombre": "ARGENTINA", "continente": "AMERICA DEL SUR", "participaciones": 13, "goles": 3, "golesencontra": 0, "faltas": 11, "puntos": 5, "difgoles": 15, "identificador": null },
    { "id": 14, "nombre": "IRAN", "continente": "ASIA", "participaciones": 14, "goles": 6, "golesencontra": 4, "faltas": 12, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 15, "nombre": "COREA DEL SUR", "continente": "ASIA", "participaciones": 15, "goles": 4, "golesencontra": 2, "faltas": 13, "puntos": 6, "difgoles": 15, "identificador": null },
    { "id": 16, "nombre": "JAPON", "continente": "ASIA", "participaciones": 16, "goles": 3, "golesencontra": 7, "faltas": 14, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 17, "nombre": "ARABIA SAUDITA", "continente": "ASIA", "participaciones": 17, "goles": 4, "golesencontra": 0, "faltas": 15, "puntos": 7, "difgoles": 0, "identificador": null },
    { "id": 18, "nombre": "ECUADOR", "continente": "AMERICA DEL SUR", "participaciones": 18, "goles": 7, "golesencontra": 6, "faltas": 16, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 19, "nombre": "URUGUAY", "continente": "AMERICA DEL SUR", "participaciones": 19, "goles": 3, "golesencontra": 4, "faltas": 17, "puntos": 4, "difgoles": 0, "identificador": null },
    { "id": 20, "nombre": "CANADA", "continente": "AMERICA DEL NORTE", "participaciones": 20, "goles": 5, "golesencontra": 2, "faltas": 18, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 21, "nombre": "GHANA", "continente": "AFRICA", "participaciones": 21, "goles": 2, "golesencontra": 2, "faltas": 20, "puntos": 6, "difgoles": 0, "identificador": null },
    { "id": 22, "nombre": "SENEGAL", "continente": "AFRICA", "participaciones": 22, "goles": 0, "golesencontra": 50, "faltas": 21, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 23, "nombre": "MARRUECOS", "continente": "AFRICA", "participaciones": 23, "goles": 0, "golesencontra": 50, "faltas": 22, "puntos": 4, "difgoles": 0, "identificador": null },
    { "id": 24, "nombre": "TUNEZ", "continente": "ASIA", "participaciones": 24, "goles": 0, "golesencontra": 15, "faltas": 23, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 25, "nombre": "PORTUGAL", "continente": "EUROPA", "participaciones": 25, "goles": 0, "golesencontra": 0, "faltas": 24, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 26, "nombre": "POLONIA", "continente": "EUROPA", "participaciones": 26, "goles": 0, "golesencontra": 0, "faltas": 25, "puntos": 4, "difgoles": 0, "identificador": null },
    { "id": 27, "nombre": "CAMERUN", "continente": "AFRICA", "participaciones": 27, "goles": 0, "golesencontra": 0, "faltas": 26, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 28, "nombre": "MEXICO", "continente": "CENTRO AMERICA", "participaciones": 28, "goles": 0, "golesencontra": 0, "faltas": 27, "puntos": 4, "difgoles": 0, "identificador": null },
    { "id": 29, "nombre": "ESTADOS UNIDOS", "continente": "AMERICA DEL NORTE", "participaciones": 29, "goles": 0, "golesencontra": 0, "faltas": 28, "puntos": 3, "difgoles": 0, "identificador": null },
    { "id": 30, "nombre": "GALES", "continente": "EUROPA", "participaciones": 30, "goles": 0, "golesencontra": 0, "faltas": 29, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 31, "nombre": "AUSTRALIA", "continente": "OCEANIA", "participaciones": 31, "goles": 15, "golesencontra": 0, "faltas": 30, "puntos": 5, "difgoles": 0, "identificador": null },
    { "id": 32, "nombre": "COSTA RICA", "continente": "CENTRO AMERICA", "participaciones": 32, "goles": 15, "golesencontra": 0, "faltas": 31, "puntos": 5, "difgoles": 0, "identificador": null }]


var listajugadores = [
    { "id": 1, "idjugador": 1, "nombre": "JUAN", "seleccion": "QATAR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 15, "faltas": 0 },
    { "id": 1, "idjugador": 2, "nombre": "jhon", "seleccion": "QATAR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 2, "idjugador": 1, "nombre": "milton", "seleccion": "ALEMANIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 2, "idjugador": 2, "nombre": "jhon", "seleccion": "ALEMANIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 3, "idjugador": 1, "nombre": "milton", "seleccion": "DINAMARCA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 3, "idjugador": 2, "nombre": "jhon", "seleccion": "DINAMARCA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 4, "idjugador": 1, "nombre": "milton", "seleccion": "BRASIL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 4, "idjugador": 2, "nombre": "jhon", "seleccion": "BRASIL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 5, "idjugador": 1, "nombre": "milton", "seleccion": "FRANCIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 5, "idjugador": 2, "nombre": "jhon", "seleccion": "FRANCIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 6, "idjugador": 1, "nombre": "milton", "seleccion": "BELGICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 6, "idjugador": 2, "nombre": "jhon", "seleccion": "BELGICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 7, "idjugador": 1, "nombre": "milton", "seleccion": "CROACIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 7, "idjugador": 2, "nombre": "jhon", "seleccion": "CROACIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 8, "idjugador": 1, "nombre": "milton", "seleccion": "ESPAÑA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 8, "idjugador": 2, "nombre": "jhon", "seleccion": "ESPAÑA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 9, "idjugador": 1, "nombre": "milton", "seleccion": "SERBIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 9, "idjugador": 2, "nombre": "jhon", "seleccion": "SERBIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 10, "idjugador": 1, "nombre": "milton", "seleccion": "INGLATERRA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 10, "idjugador": 2, "nombre": "jhon", "seleccion": "INGLATERRA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 11, "idjugador": 1, "nombre": "milton", "seleccion": "SUIZA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 11, "idjugador": 2, "nombre": "jhon", "seleccion": "SUIZA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 12, "idjugador": 1, "nombre": "milton", "seleccion": "PAISES BAJOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 12, "idjugador": 2, "nombre": "jhon", "seleccion": "PAISES BAJOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 13, "idjugador": 1, "nombre": "milton", "seleccion": "ARGENTINA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 13, "idjugador": 2, "nombre": "jhon", "seleccion": "ARGENTINA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 14, "idjugador": 1, "nombre": "milton", "seleccion": "IRAN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 14, "idjugador": 2, "nombre": "jhon", "seleccion": "IRAN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 15, "idjugador": 1, "nombre": "milton", "seleccion": "COREA DEL SUR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 15, "idjugador": 2, "nombre": "jhon", "seleccion": "COREA DEL SUR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 16, "idjugador": 1, "nombre": "milton", "seleccion": "JAPON", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 16, "idjugador": 2, "nombre": "jhon", "seleccion": "JAPON", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 17, "idjugador": 1, "nombre": "milton", "seleccion": "ARABIA SAUDITA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 17, "idjugador": 2, "nombre": "jhon", "seleccion": "ARABIA SAUDITA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 18, "idjugador": 1, "nombre": "milton", "seleccion": "ECUADOR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 18, "idjugador": 2, "nombre": "jhon", "seleccion": "ECUADOR", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 19, "idjugador": 1, "nombre": "milton", "seleccion": "URUGUAY", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 19, "idjugador": 2, "nombre": "jhon", "seleccion": "URUGUAY", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 20, "idjugador": 1, "nombre": "milton", "seleccion": "CANADA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 20, "idjugador": 2, "nombre": "jhon", "seleccion": "CANADA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 21, "idjugador": 1, "nombre": "milton", "seleccion": "GHANA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 21, "idjugador": 2, "nombre": "jhon", "seleccion": "GHANA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 22, "idjugador": 1, "nombre": "milton", "seleccion": "SENEGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 22, "idjugador": 2, "nombre": "jhon", "seleccion": "SENEGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 23, "idjugador": 1, "nombre": "milton", "seleccion": "MARRUECOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 23, "idjugador": 2, "nombre": "jhon", "seleccion": "MARRUECOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 24, "idjugador": 1, "nombre": "milton", "seleccion": "TUNEZ", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 24, "idjugador": 2, "nombre": "jhon", "seleccion": "TUNEZ", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 25, "idjugador": 1, "nombre": "bichardo", "seleccion": "PORTUGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 25, "idjugador": 2, "nombre": "bicho", "seleccion": "PORTUGAL", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 26, "idjugador": 1, "nombre": "milton", "seleccion": "POLONIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 26, "idjugador": 2, "nombre": "jhon", "seleccion": "POLONIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 27, "idjugador": 1, "nombre": "milton", "seleccion": "CAMERUN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 27, "idjugador": 2, "nombre": "jhon", "seleccion": "CAMERUN", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 28, "idjugador": 1, "nombre": "milton", "seleccion": "MEXICO", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 28, "idjugador": 2, "nombre": "jhon", "seleccion": "MEXICO", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 29, "idjugador": 1, "nombre": "milton", "seleccion": "ESTADOS UNIDOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 29, "idjugador": 2, "nombre": "jhon", "seleccion": "ESTADOS UNIDOS", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 30, "idjugador": 1, "nombre": "milton", "seleccion": "GALES", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 30, "idjugador": 2, "nombre": "jhon", "seleccion": "GALES", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 31, "idjugador": 1, "nombre": "milton", "seleccion": "AUSTRALIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 31, "idjugador": 2, "nombre": "jhon", "seleccion": "AUSTRALIA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 32, "idjugador": 1, "nombre": "milton", "seleccion": "COSTA RICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 0, "faltas": 0 },
    { "id": 32, "idjugador": 2, "nombre": "ELBICHITO", "seleccion": "COSTA RICA", "nacimiento": 22 / 10 / 2001, "estatura": 170, "posicion": "DC", "goles": 15, "faltas": 0 }
]